### ISSUE TITLE
No Linux version? REALLY?

### ISSUE THREAD

**Issue by bipolarmorgan** [jeremy-jr-benthum/onion-browser-button#19]
Epic fail, please provide a linux version. Or the source code, so we can compile it ourselves. Thanks.

**Comment by ghost** [comment]
You can use wine to run it. It works great for me.

Now, I do agree the source code should be uploaded. This is GitHub, _**the**_ open source platform, it makes no sense at all to leave out the source code here.

**Comment by SwanX1** [comment]
> You can use wine to run it. It works great for me.

I want a native solution instead of using wine, however this extension works really well on windows, so I will keep using it on linux with wine.

**Comment by bipolarmorgan** [comment]
> You can use wine to run it. It works great for me.
> 
> Now, I do agree the source code should be uploaded. This is GitHub, _**the**_ open source platform, it makes no sense at all to leave out the source code here.

Uh, no kidding? i could also just run it on my windows box, but what's your point? I was asking for linux, telling me about wine, as if i didn't know, doesn't really mean anything to me. If i wanted to do that, I wouldn't have made the post. :)

**Comment by F1uk369** [comment]
I've added a pull request for a Linux support patch I made, however in the meantime, use my repository: https://github.com/F1uk369/onion-browser-button
